version: '1'

services:
  db:
    container_name: db
    image: postgres:16.1
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "2121"
    volumes:
      - ./.docker:/var/lib/postgresql
    ports:
      - 8090:5432 #TODO: Close ports, after gateway setup


  mc-core:
    container_name: mc-core
    build: ./mc-core
    restart: always
    ports:
      - 8081:8080 #TODO: Close port, after gateway setup

  mc-archive:
    container_name: mc-archive
    build: ./mc-archive
    depends_on:
      - db
    restart: always
    ports:
      - 8082:8080 #TODO: Close ports, after gateway setup


  mc-gateway:
    container_name: mc-gateway
    build: ./mc-gateway
    restart: always
    ports:
      - 8083:8080
