version: '1'

services:
  db:
    container_name: db
    image: postgres:16.1
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "2121"
    volumes:
      - ./.docker:/var/lib/postgresql

  mc-core:
    container_name: mc-core
    build: ./mc-core
    restart: always
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0

  mc-archive:
    container_name: mc-archive
    build: ./mc-archive
    depends_on:
      - db
    restart: always

  mc-gateway:
    container_name: mc-gateway
    build: ./mc-gateway
    restart: always
    ports:
      - 80:8080
